### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by davelab6** [jpamental/variable-fonts#146]
@jpamental small question, is this site using the built-in Jekyll continuous integration feature called Github Pages; if so, can then there be no `master` branch, just a `gh-pages` branch?

**Comment by jpamental** [comment]
We are using the built-in CI. But I'm a bit hesitant to make any changes just yet (let's wait at least until we know where it will live), and then establish a better practice for how we manage changes/additions. I've certainly not been enforcing my own better practices while i was the only one working on it, so I'd rather get to 'launched' and then get back to a better process of branch/review/marge/deploy

**Comment by davelab6** [comment]
Now that's resolved, might be time for a branch clean up?

I suggest adding a CONTRIBUTING.md file for that info :)
