### ISSUE TITLE
Global layout has errant quote shifting layout

### ISSUE THREAD

**Issue by arrowtype** [jpamental/variable-fonts#163]
It seems that an errant quote is messing up the layout of all pages. This is more noticeable on pages with backgrounds, such as the "Designing with Variable Fonts" and "Implementing Variable Fonts."

![image](https://user-images.githubusercontent.com/45946693/75930460-9ccfbf80-5e40-11ea-8368-fdc92d979ff2.png)

![image](https://user-images.githubusercontent.com/45946693/75930566-ddc7d400-5e40-11ea-8adc-7be5d07ef007.png)

![image](https://user-images.githubusercontent.com/45946693/75930574-e3bdb500-5e40-11ea-86eb-b982da3dfbff.png)

Browsers: macOS Chrome, iOS Safari

**Comment by jpamental** [comment]
Got it - thanks @arrowtype !
