### ISSUE TITLE
Text overlaps graphics at some sizes

### ISSUE THREAD

**Issue by rsheeter** [jpamental/variable-fonts#166]
Loving the site. Nit:

![image (2)](https://user-images.githubusercontent.com/6466432/75940698-993d3800-5e42-11ea-9d5b-786e19e4ba45.png)

Observed on Chrome 80.0.3987.122 (Official Build) (64-bit), Linux.

**Comment by jpamental** [comment]
I hear ya @rsheeter — that’s on my list!

**Comment by jpamental** [comment]
And thank you! Hoping I can end up serving more from the API when more axes are supported in Recursive & Roboto Extremo :)

**Comment by jpamental** [comment]
Fixed with #167
