### ISSUE TITLE
implementing page: Improve visual design of GF screenshots 

### ISSUE THREAD

**Issue by davelab6** [jpamental/variable-fonts#173]
The red ovals on the screenshots (eg `/assets/img/gf_ui_1.png`) do not look great

I suggest improving them with a 'spotlight' treatment, where a oval mask is applied to a semi-transparent dark layer to highlight the same areas

**Comment by davelab6** [comment]
Potentially a short GIF showing the interaction with the elements could also be good. www.getkap.co is nice for this on macOS :)

**Comment by davelab6** [comment]
Ah it was https://boinx.com/mousepose/ that makes the kind of screenshots I was thinking of

**Comment by jpamental** [comment]
@davelab6 I decided not to add animated GIFs as they don't scale nicely (for viewport) but I think these ended up working nicely
