### ISSUE TITLE
variable axis glyph substitution not working on Safari; can be fixed with hack

### ISSUE THREAD

**Issue by arrowtype** [jpamental/variable-fonts#175]
In the opening banner, letters like `r` only have their correct letterforms in Chrome and Firefox. On Safari, they have the incorrect letterforms, because Safari has a bugs around `rvrn`.

Letterspacing block rvrn: https://bugs.webkit.org/show_bug.cgi?id=206898

& 

Single-character strings block `rvrn` (that seems to be the main culprit here): https://arrowtype.github.io/recursive/gsub-bug-and-hack_fix-safari/index.html

On Chrome & Firefox, letters have this appearance:

![image](https://user-images.githubusercontent.com/45946693/76115423-1dfc9300-5fb6-11ea-8b99-b8924d8c6c40.png)

On Safari, they have this appearance (the `r`, `i`, and `l` all have their default forms rather than their mono-specific alternates):

![image](https://user-images.githubusercontent.com/45946693/76115343-01605b00-5fb6-11ea-8ed6-6621cd355775.png)

One hack to make things work is to apply a stylistic set that does nothing, such as `ss19`:

![image](https://user-images.githubusercontent.com/45946693/76115295-ec83c780-5fb5-11ea-82f7-e31c6bf7528d.png)

Another hack is to add a zero-width space into each span.

**Comment by jpamental** [comment]
Thanks @arrowtype - fix deployed using `font-feature-settings: 'ss19' 1;`
