### ISSUE TITLE
footer: Alt copy/links to Github?

### ISSUE THREAD

**Issue by davelab6** [jpamental/variable-fonts#176]
www.web.dev has a nice footer copy

<img width="298" alt="Screen Shot 2020-03-06 at 4 12 25 PM" src="https://user-images.githubusercontent.com/261579/76122976-653e5000-5fc5-11ea-9a14-ac0e70e05aff.png">

- [ ] "File a bug"
- [ ] "View source"

This feels more actionable and recognizable than "Contribute to this site on Github"... what do you think @jpamental ? :)

**Comment by jpamental** [comment]
I've rewritten this a bit as it does help balance the footer a bit but will likely be reorganizing the lot of it this week
