### ISSUE TITLE
font-width or font-stretch?

### ISSUE THREAD

**Issue by fjanon** [jpamental/variable-fonts#201]
I could not find any reference to font-width used in the font stretch example

Text:

  p {
    font-stretch: 89%;
  }

Dynamic example:
.text {
   font-width: %;
}

Web debugger:

font-stretch: calc( var(--text-vf-wdth) * 1%);

not font-width

**Comment by jpamental** [comment]
Hi @fjanon - that was my mistake somewhere along the line. The correct CSS attribute is `font-stretch`, but it is acting upon the `wdth` axis from the font. It's been corrected on the site now. Thank you, and sorry for the confusion!
