### ISSUE TITLE
Third-party JS in use

### ISSUE THREAD

**Issue by jpamental** [jpamental/variable-fonts#27]
Hi there,

There are two JS libraries in use: one Google project (Prettify) and FontFaceObserver. I've cleaned up the code organization to put them both in a top-level directory `third_party` and have included the license files.

Evan - hoping you're the right Evan to tag in on this! Dave Crossland sent me an email saying these should be approved by you. I'm assuming that the Google project will be fine, and am hoping the same will hold true for Font Face Observer. That is being used to better manage the font loading/display experience for the site.

Please don't hesitate to get in touch if you need more clarification.

Thanks,

Jason

Google Code Prettify
https://github.com/google/code-prettify

Font Face Observer
https://github.com/bramstein/fontfaceobserver

**Comment by davelab6** [comment]
Those 2 are approved! 

However, I'm still seeing a security error:

![Screen Shot 2019-12-18 at 4 22 59 PM](https://user-images.githubusercontent.com/261579/71124374-b3a43580-21b2-11ea-9154-54ea1e8ed6ba.png)

I guess the fix may be to regenerated `package-lock.json`

**Comment by davelab6** [comment]
Are these gulp/webpack dependencies needed? 
https://github.com/googlefonts/typography/blob/dd69542702bf26202e03fc0510afc38517e940ac/package.json#L20-L26

**Comment by jpamental** [comment]
Yes - those are necessary to pull in the Material Design components and build the project (compiling sass, concatenating files, pulling in Material includes)

**Comment by jpamental** [comment]
Worth noting that the node_modules directory itself is not included in the repository, nor are they required to build the Jekyll site itself. They're only needed to do the build in the local dev environment.

**Comment by davelab6** [comment]
I'm still seeing the security alert :(

**Comment by jpamental** [comment]
@davelab6 I can't see the security alerts. Can you paste in the text so I can see what might be causing them?

**Comment by davelab6** [comment]
Ah yes, thanks for pointing that out 😅

![Screenshot_20200102-202132](https://user-images.githubusercontent.com/261579/71702438-84d6b380-2d9d-11ea-9ff2-df3f5443d7eb.png)

**Comment by jpamental** [comment]
@davelab6 I think this should be all set now!
