### ISSUE TITLE
VF site IA

### ISSUE THREAD

**Issue by jpamental** [jpamental/variable-fonts#7]
Using this issue to track the development of the information architecture & sitemap.

Doc is here:
https://docs.google.com/drawings/d/1hXB99kQsWGx1EE7ViIdArDa1PLlul3xsvXwH6N2xbqo/edit

**Comment by davelab6** [comment]
Nice! Here's the current snap shot:

![VF Education Site IA](https://user-images.githubusercontent.com/261579/74762887-bb349900-524c-11ea-9cea-a1b8a275fe8c.png)

@jpamental do you want to assign this to me, and I'll go through that to map it the site today and file issues, or comments here? :)

**Comment by jpamental** [comment]
@davelab6 as we discussed today I'm writing a sort of 'colophon' page that will talk about how this site was designed and built, which will address aspects of how VFs benefit UI, accessibility, reading, typographic design, etc since I make use of all those things in the design and development of the site itself. I'll have a draft of that probably end of day tomorrow
